apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-ingress
  annotations:
    # This is your MetalLB "Sticky IP"
    metallb.universe.tf/loadBalancerIPs: 10.0.80.100
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All